[package]
name = "machoke"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = "0.18.2"
id3 = "1.16.0"
futures = "0.3.31"