name: 发布流程

on:
  push:
    tags:
      - v**

jobs:
  build:
    strategy:
      matrix:
        include:
          - source: machoke
            target: linux-machoke
            os: ubuntu-latest

    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build-rust-static-library
        working-directory: xglib
        run: cargo build --release
      - name: setup qt6
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.8.2
          target: desktop
      - name: build application
        run: cmake -B build/release && cmake --build build/release
      - name: 查看
        run: ls -l build/release/
      - name: 改名
        run: mv build/release/${{ matrix.source }} build/release/${{ matrix.target }}
      - name: 上传
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ github.ref_name }} > /dev/null 2>&1 || gh release create ${{ github.ref_name }} --generate-notes
          gh release upload ${{ github.ref_name }} ./build/release/${{ matrix.target}}
